name: Kacper Bojakowski
title: Technical Writing for Translators
description: A guide for translators on how to retrain as a technical writer.
remote_theme: kacperbojakowski/just-the-docs

color_scheme: kb-color

back_to_top: true

footer_content: ""

back_to_top_text: "â¬†"
